# Generated by Django 5.2.7 on 2025-10-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_experience_profile_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
