# Generated by Django 5.2.7 on 2025-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_bio_profile_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_institute',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification_other',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
