# Generated by Django 5.2.7 on 2025-11-01 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_subjects_list_profile_grade_10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_10',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_11',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_12',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_8',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_9',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='grade_nursery_to_5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hourly_rate_min',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_grade_10',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_grade_11',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_grade_12',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_grade_6',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_grade_7',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_grade_8',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_grade_9',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rate_nursery_to_5',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subject',
        ),
        migrations.CreateModel(
            name='TutorGradeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('nursery_to_5', 'Nursery to 5th'), ('grade_6', '6th'), ('grade_7', '7th'), ('grade_8', '8th'), ('grade_9', '9th'), ('grade_10', '10th'), ('grade_11', '11th'), ('grade_12', '12th')], max_length=20)),
                ('subjects', models.TextField()),
                ('rate_online', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_student_home', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rate_my_home', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_rates', to='users.profile')),
            ],
            options={
                'ordering': ['grade'],
                'unique_together': {('profile', 'grade')},
            },
        ),
    ]
