# Generated by Django 5.2.7 on 2025-11-03 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_address_line1_profile_address_line2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('time_slot', models.CharField(choices=[('06:00-07:00', '06:00 AM - 07:00 AM'), ('07:00-08:00', '07:00 AM - 08:00 AM'), ('08:00-09:00', '08:00 AM - 09:00 AM'), ('09:00-10:00', '09:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 01:00 PM'), ('13:00-14:00', '01:00 PM - 02:00 PM'), ('14:00-15:00', '02:00 PM - 03:00 PM'), ('15:00-16:00', '03:00 PM - 04:00 PM'), ('16:00-17:00', '04:00 PM - 05:00 PM'), ('17:00-18:00', '05:00 PM - 06:00 PM'), ('18:00-19:00', '06:00 PM - 07:00 PM'), ('19:00-20:00', '07:00 PM - 08:00 PM'), ('20:00-21:00', '08:00 PM - 09:00 PM'), ('21:00-22:00', '09:00 PM - 10:00 PM')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='users.profile')),
            ],
            options={
                'verbose_name': 'Tutor Availability',
                'verbose_name_plural': 'Tutor Availabilities',
                'ordering': ['day', 'time_slot'],
                'unique_together': {('profile', 'day', 'time_slot')},
            },
        ),
    ]
