# Generated by Django 5.2.7 on 2025-11-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_tutoravailability_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoravailability',
            name='time_slot',
            field=models.CharField(choices=[('04:00-05:00', '04:00 AM - 05:00 AM'), ('05:00-06:00', '05:00 AM - 06:00 AM'), ('06:00-07:00', '06:00 AM - 07:00 AM'), ('07:00-08:00', '07:00 AM - 08:00 AM'), ('08:00-09:00', '08:00 AM - 09:00 AM'), ('09:00-10:00', '09:00 AM - 10:00 AM'), ('10:00-11:00', '10:00 AM - 11:00 AM'), ('11:00-12:00', '11:00 AM - 12:00 PM'), ('12:00-13:00', '12:00 PM - 01:00 PM'), ('13:00-14:00', '01:00 PM - 02:00 PM'), ('14:00-15:00', '02:00 PM - 03:00 PM'), ('15:00-16:00', '03:00 PM - 04:00 PM'), ('16:00-17:00', '04:00 PM - 05:00 PM'), ('17:00-18:00', '05:00 PM - 06:00 PM'), ('18:00-19:00', '06:00 PM - 07:00 PM'), ('19:00-20:00', '07:00 PM - 08:00 PM'), ('20:00-21:00', '08:00 PM - 09:00 PM')], max_length=20),
        ),
    ]
