# Generated by Django 5.2.7 on 2025-11-03 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_tutoravailability_time_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoravailability',
            options={'verbose_name': 'Tutor Availability', 'verbose_name_plural': 'Tutor Availabilities'},
        ),
        migrations.RenameField(
            model_name='tutoravailability',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.AlterUniqueTogether(
            name='tutoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tutoravailability',
            name='sunday_slots',
            field=models.JSONField(blank=True, default=list, help_text='Time slots for Sunday'),
        ),
        migrations.AddField(
            model_name='tutoravailability',
            name='time_slots',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tutoravailability',
            name='weekday_slots',
            field=models.JSONField(blank=True, default=list, help_text='Common time slots for Mon-Sat'),
        ),
        migrations.AlterField(
            model_name='tutoravailability',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='users.profile'),
        ),
        migrations.RemoveField(
            model_name='tutoravailability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tutoravailability',
            name='time_slot',
        ),
    ]
