# Generated by Django 5.2.7 on 2025-11-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_tutoravailability_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoravailability',
            name='sunday_slots',
        ),
        migrations.RemoveField(
            model_name='tutoravailability',
            name='weekday_slots',
        ),
        migrations.AlterField(
            model_name='tutoravailability',
            name='time_slots',
            field=models.JSONField(blank=True, default=list, help_text='Time slots for Mon-Sat'),
        ),
    ]
