# Generated by Django 5.2.7 on 2026-06-22 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_bookingrequest_grade_bookingrequest_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bookingrequest',
            unique_together={('student', 'tutor')},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paise')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='users.bookingrequest')),
            ],
        ),
    ]
