# Generated by Django 6.0.7 on 2026-07-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_tutorreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingrequest",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("online", "Online"),
                    ("student_home", "At Student's Home"),
                    ("my_home", "At Tutor's Home"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
