# Generated by Django 6.0.7 on 2026-07-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_bookingrequest_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="free_contacts_used",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
