# Generated by Django 6.0.7 on 2026-08-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_profile_free_contacts_used"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpayWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=100, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("processing_note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
