# Generated by Django 6.0.7 on 2026-08-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_razorpaywebhookevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingrequest",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, help_text="Price in INR per month", null=True
            ),
        ),
    ]
