# Generated by Django 6.0.7 on 2026-08-17 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Shown on the blog list page and used as the meta description if left blank there.",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="HTML content, authored via the admin."),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("exam_tips", "Exam Tips"),
                            ("subject_guides", "Subject Guides"),
                            ("parenting", "Parenting"),
                            ("tutor_advice", "Tutor Advice"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated, free text.",
                        max_length=255,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                (
                    "featured_image",
                    models.FileField(blank=True, null=True, upload_to="blog/"),
                ),
                ("related_city", models.CharField(blank=True, max_length=100)),
                ("related_subject", models.CharField(blank=True, max_length=100)),
                ("related_board", models.CharField(blank=True, max_length=100)),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
